import type { Metadata } from "next";
import {ReactNode} from "react";
import "./globals.css";

import {Providers} from "./providers"     // web3 wallet provider
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Airdrop Sender App",
  description: "Generated by Next.js app",
};

/**
 * Every page in our dapp will have Providers available
 * 
 * @param props 
 * @returns 
 */
export default function RootLayout(props: { children: ReactNode}){
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header/>
          {props.children}
        </Providers>
      </body>
    </html>
  );
}
